require('common');

local settings = T{ };
settings["Average_WS"] = false;
settings["Melee"] = true;
settings["Running_Acc"] = true;
settings["DPS_Graph_Height"] = 50;
settings["Rank_Cutoff"] = 6;
settings["Show_Filter"] = true;
settings["Ranged"] = false;
settings["Pet_Melee"] = false;
settings["Weaponskill"] = true;
settings["Display_Mode"] = 1;
settings["Pet_Acc"] = false;
settings["Show_Clock"] = false;
settings["Pet_WS"] = false;
settings["Ability"] = false;
settings["Pet_Ranged"] = false;
settings["Pet_Ability"] = false;
settings["Attack_Speed"] = true;
settings["Condensed_Numbers"] = false;
settings["Show_DPS_Graph"] = false;
settings["Healing"] = false;
settings["Total_Acc"] = false;
settings["Global_DPS"] = false;
settings["Name_Colors"] = true;
settings["DPS"] = true;
settings["Jobs"] = false;
settings["Crit"] = false;
settings["Grand_Totals"] = false;
settings["Include_SC_Damage"] = false;
settings["Magic"] = true;
settings["Deaths"] = false;

return settings;
