require('common');

local settings = T{ };
settings["Visible"] = T{ };
settings["Kill_Speed"] = true;
settings["Total_XP"] = true;
settings["To_Next_Level"] = true;
settings["Base_Rate"] = false;
settings["Boost_Item_Default_Name"] = "Anniversary Ring";
settings["XP_Job"] = true;
settings["Boost_Progress"] = true;
settings["Max_Chain"] = false;
settings["XP_Boost_Rate"] = false;
settings["Average_XP"] = false;
settings["Show_Background"] = false;
settings["XP_Boost_Max"] = false;
settings["Boost_Item_Max"] = -1;
settings["Small_Bars"] = true;
settings["Time_To_Level"] = true;
settings["Visible"][1] = true;
settings["Boost_Item_Rate"] = -1;
settings["Boost_EXP"] = 0;
settings["Boost_Item_Name"] = "Unknown";
settings["XP_Mini"] = false;
settings["X"] = 100;
settings["Boost_Item_Default_Index"] = 1;
settings["Boost_Default"] = false;
settings["Y"] = 100;
settings["XP_Boost_Item"] = false;
settings["Zone_Time"] = false;
settings["XP_Progress"] = true;

return settings;
